# Site settings
title: Dan
tagline: This is a simple holding page for the benefit of our QA workshop

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#441199"

# contact
author:
  name: Dan Buckland
  url: http://github.com/danbuckland

twitter_username: danbuckland
github_username:  danbuckland
github_url: "https://github.com/danbuckland/boilerplate.site"

# Others
markdown: redcarpet

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
